{orcamento.i}

DEFINE INPUT  PARAMETER iMes AS INTEGER    NO-UNDO.
DEFINE INPUT  PARAMETER iOrc AS INTEGER    NO-UNDO.
DEFINE OUTPUT PARAMETER TABLE FOR tt-acomp.

RUN criaTTacomp (INPUT iMes, INPUT iMes, INPUT iOrc).

