DEFINE OUTPUT PARAMETER pReturn                  AS ROWID      NO-UNDO.

DEFINE NEW GLOBAL SHARED VARIABLE glImplantar    AS LOGICAL    NO-UNDO.
DEFINE NEW GLOBAL SHARED VARIABLE gcFiltro       AS CHARACTER  NO-UNDO.
DEFINE NEW GLOBAL SHARED VARIABLE gcFiltroIniFim AS CHARACTER  NO-UNDO.
DEFINE NEW GLOBAL SHARED VARIABLE hProgsMenu     AS HANDLE     NO-UNDO EXTENT 200.
DEFINE NEW GLOBAL SHARED VARIABLE iProgsCont     AS INTEGER    NO-UNDO.

{func\tt_filtro.i}

{seg.i}
