DEFINE TEMP-TABLE tt-filtro
    FIELD campo AS CHARACTER FORMAT "X(20)" COLUMN-LABEL "Campo"
    FIELD valor AS CHARACTER FORMAT "X(27)" COLUMN-LABEL "Valor"
    FIELD orig  AS CHARACTER
    FIELD tipo  AS CHARACTER
    FIELD formato AS CHARACTER.
